services:
  riven_server:
    image: riven_server
    hostname: riven-server
    build:
      context: .
      dockerfile: Dockerfile
      target: development
      args:
        - MEMGPT_ENVIRONMENT=DEVELOPMENT
    depends_on:
      - riven_db
    env_file:
      - .env
    environment:
      - WATCHFILES_FORCE_POLLING=true

    volumes:
      - ./riven:/riven
      - ~/.riven/credentials:/root/.riven/credentials
      - ./configs/server_config.yaml:/root/.riven/config
      - ./CONTRIBUTING.md:/CONTRIBUTING.md
      - ./tests/pytest_cache:/riven/.pytest_cache
      - ./tests/pytest.ini:/riven/pytest.ini
      - ./pyproject.toml:/pyproject.toml
      - ./tests:/tests
    ports:
      - "8083:8083"
      - "8283:8283"
